
# Brazilian Airline Historical Series Analysis

#### Frederico Horst

### Data Sources:
- Historical air fares by origin, destination and airline: available at [ANAC website](https://sistemas.anac.gov.br/sas/downloads/view/frmDownload.aspx)
- Inflation data, using IPCA index: available at [IBGE website](https://www.ibge.gov.br/estatisticas/economicas/precos-e-custos/9256-indice-nacional-de-precos-ao-consumidor-amplo.html?=&t=series-historicas)
- More information on air fares on [ANAC website](https://www.anac.gov.br/assuntos/dados-e-estatisticas/mercado-do-transporte-aereo)

### Goals:
- Build a metrics database: average price, standard deviation and quartils by year and route;
<!-- - Build a database for historical deflated prices.
- Calculate the confidence interval for the average price range by route, considering a 95% confidence.
- Confidence intervals will be calculated by route, not considering airline differences. We want to take a closer look to the consumer point of view. -->

In [1]:
from files_processor import FilesProcessor

df = FilesProcessor().process_files()
df.head()

,Year,Month,Airline,OriginICAO,DestinationICAO,Fare,Seats,YearMonth,ICAO_x,OriginCity,Origin,ICAO_y,DestinationCity,Destination,Route
0,2002,1,GLO,SBPA,SBBR,397.0,51,2002-01,SBPA,Aeroporto Internacional de Porto Alegre / Salg...,POA,SBBR,Aeroporto Internacional de Brasília / Presiden...,BSB,POA >> BSB
1,2002,1,GLO,SBSV,SBRF,272.0,5,2002-01,SBSV,Aeroporto Internacional de Salvador / Deputado...,SSA,SBRF,Aeroporto Internacional do Recife/ Guararapes ...,REC,SSA >> REC
2,2002,1,GLO,SBFL,SBGL,223.0,196,2002-01,SBFL,Aeroporto Internacional de Florianópolis / Her...,FLN,SBGL,Aeroporto Internacional do Rio de Janeiro / Ga...,GIG,FLN >> GIG
3,2002,1,GLO,SBGL,SBSP,96.0,615,2002-01,SBGL,Aeroporto Internacional do Rio de Janeiro / Ga...,GIG,SBSP,Aeroporto Internacional de São Paulo / Congonhas,CGH,GIG >> CGH
4,2002,1,GLO,SBGL,SBRF,340.0,297,2002-01,SBGL,Aeroporto Internacional do Rio de Janeiro / Ga...,GIG,SBRF,Aeroporto Internacional do Recife/ Guararapes ...,REC,GIG >> REC

In [6]:
dfX = df[['Route', 'YearMonth', 'Fare', 'Seats']].copy()
dfX = dfX[dfX['Route'] == "SBPA >> SBSP"]

dfX.head(15)

            Route YearMonth    Fare  Seats
7    SBPA >> SBSP   2002-01  269.00    184
26   SBPA >> SBSP   2002-01  323.00      4
38   SBPA >> SBSP   2002-01  212.00    318
81   SBPA >> SBSP   2002-01  259.00     88
103  SBPA >> SBSP   2002-01  250.00    114
126  SBPA >> SBSP   2002-01  202.00    356
138  SBPA >> SBSP   2002-01  193.00    276
169  SBPA >> SBSP   2002-01  183.00   4234
292  SBPA >> SBSP   2002-01  231.00    354
328  SBPA >> SBSP   2002-01  221.00    248
338  SBPA >> SBSP   2002-01  314.00    124
375  SBPA >> SBSP   2002-01  295.00    118
464  SBPA >> SBSP   2002-01  240.00    212
498  SBPA >> SBSP   2002-01  392.66     64
689  SBPA >> SBSP   2002-01  303.00    559

In [11]:
# calculate the weighted average fare, standard deviation and total seats for each route and month
# considering seats as weights for the average fare

import pandas


metrics = dfX.groupby(['Route', 'YearMonth']).apply(lambda x: pandas.Series({
    'WeightedAverageFare': (x['Fare'] * x['Seats']).sum() / x['Seats'].sum(),
    'FareStdDev': x['Fare'].std(),
    'TotalSeats': x['Seats'].sum()
})).reset_index()



metrics.head(15)

           Route YearMonth  WeightedAverageFare  FareStdDev  TotalSeats
0   SBPA >> SBSP   2002-01           240.688250  110.611203     24967.0
1   SBPA >> SBSP   2002-02           249.510584  110.597438     22979.0
2   SBPA >> SBSP   2002-03           248.343062  104.194381     26280.0
3   SBPA >> SBSP   2002-04           207.690850  143.523162     28097.0
4   SBPA >> SBSP   2002-05           202.736040  117.973958     25686.0
5   SBPA >> SBSP   2002-06           263.424251  148.965174     36766.0
6   SBPA >> SBSP   2002-07           374.047241  137.762587     26560.0
7   SBPA >> SBSP   2002-08           374.057697  147.288215     25255.0
8   SBPA >> SBSP   2002-09           366.527272  132.043089     29225.0
9   SBPA >> SBSP   2002-10           376.992323  175.779228     15438.0
10  SBPA >> SBSP   2002-11           443.331303  181.545572     28370.0
11  SBPA >> SBSP   2002-12           432.170896  182.368386     17470.0
12  SBPA >> SBSP   2003-01           424.451734  188.546431     14349.0
13  SBPA >> SBSP   2003-02           316.902875  212.064775     19159.0
14  SBPA >> SBSP   2003-03           268.429338  216.099197     31753.0