
# Brazilian Airline Historical Series Analysis

#### Frederico Horst

### Data Sources:
- Historical air fares by origin, destination and airline: available at [ANAC website](https://sistemas.anac.gov.br/sas/downloads/view/frmDownload.aspx)
- Inflation data, using IPCA index: available at [IBGE website](https://www.ibge.gov.br/estatisticas/economicas/precos-e-custos/9256-indice-nacional-de-precos-ao-consumidor-amplo.html?=&t=series-historicas)
- More information on air fares on [ANAC website](https://www.anac.gov.br/assuntos/dados-e-estatisticas/mercado-do-transporte-aereo)

### Goals:
- Build a metrics database: average price, standard deviation and quartils by year and route;
<!-- - Build a database for historical deflated prices.
- Calculate the confidence interval for the average price range by route, considering a 95% confidence.
- Confidence intervals will be calculated by route, not considering airline differences. We want to take a closer look to the consumer point of view. -->

In [1]:
from files_processor import FilesProcessor

df, metrics, route_variability = FilesProcessor().process_files()
df = None
metrics.head(15)

/Users/fred/Projects/flight-fares-analysis/files_processor.py:73: RuntimeWarning: invalid value encountered in scalar divide
  variance = (weights * (values - average) ** 2).sum() / (weights.sum() - 1)
/Users/fred/Projects/flight-fares-analysis/files_processor.py:73: RuntimeWarning: invalid value encountered in scalar divide
  variance = (weights * (values - average) ** 2).sum() / (weights.sum() - 1)

,RouteAgg,Route,YearMonth,WeightedAverageFare,FareStdDev,TotalSeats,CoefficientVariation,IPCAIndex,WeightedAverageFareReal,FareStdDevReal
0,AJU >> BEL,AJU >> BEL,2010-07,517.963648,245.339151,159.0,0.473661,3111.05,885.776859,419.557904
1,AJU >> BEL,AJU >> BEL,2010-08,474.473939,239.542604,165.0,0.504859,3112.29,811.081222,409.481938
2,AJU >> BEL,AJU >> BEL,2010-09,586.108156,254.796107,141.0,0.434725,3126.29,997.425676,433.606283
3,AJU >> BEL,AJU >> BEL,2010-10,496.748429,218.305165,191.0,0.439468,3149.74,839.061583,368.740929
4,AJU >> BEL,AJU >> BEL,2010-11,477.686829,253.875096,205.0,0.531468,3175.88,800.223356,425.292826
5,AJU >> BEL,AJU >> BEL,2010-12,316.785982,202.687740,224.0,0.639825,3195.89,527.358771,337.417573
6,AJU >> BEL,AJU >> BEL,2012-01,729.279337,419.354247,181.0,0.575026,3422.79,1133.563085,651.827730
7,AJU >> BEL,AJU >> BEL,2012-02,727.327007,407.303300,147.0,0.560000,3438.19,1125.464709,630.260510
8,AJU >> BEL,AJU >> BEL,2012-03,425.716070,321.312865,257.0,0.754759,3445.41,657.371959,496.157139
9,AJU >> BEL,AJU >> BEL,2012-04,455.820754,364.807687,252.0,0.800331,3467.46,699.382362,559.737704
10,AJU >> BEL,AJU >> BEL,2012-05,593.369310,395.333542,174.0,0.666252,3479.94,907.163076,604.399294
11,AJU >> BEL,AJU >> BEL,2012-06,528.829898,374.949884,293.0,0.709018,3482.72,807.847677,572.778495
12,AJU >> BEL,AJU >> BEL,2012-07,489.956195,369.910546,226.0,0.754987,3497.70,745.258154,562.660201
13,AJU >> BEL,AJU >> BEL,2012-08,359.136304,267.630711,322.0,0.745207,3512.04,544.041333,405.423142
14,AJU >> BEL,AJU >> BEL,2012-09,392.806783,259.063436,286.0,0.659519,3532.06,591.674629,390.220507

In [ ]:
route_variability.sort_values(by='CoefficientVariation', ascending=False).head(15)

,RouteAgg,AverageFareReal,FareRealStdDev,MinFareReal,MaxFareReal,MonthsAvailable,TotalSeats,CoefficientVariation
0,AJU >> BEL,874.123672,220.521590,527.358771,1967.983822,102.0,31576.0,0.252277
1,AJU >> BPS,443.591012,173.884875,230.750142,1335.401629,101.0,6207.0,0.391994
2,AJU >> BSB,476.667062,106.955774,319.977695,863.268562,102.0,502593.0,0.224383
3,AJU >> BVB,1016.979359,315.783042,371.155861,2808.872128,101.0,3131.0,0.310511
4,AJU >> CFB,709.160983,288.077253,309.141720,1326.499376,20.0,52.0,0.406223
5,AJU >> CGB,698.404261,145.853316,405.430172,1546.474163,102.0,43079.0,0.208838
6,AJU >> CGH,464.899634,101.771927,310.958955,897.793487,102.0,354684.0,0.218912
7,AJU >> CGR,560.643827,93.588428,352.817159,1066.264291,102.0,44696.0,0.166930
8,AJU >> CNF,494.490638,101.348073,324.050852,866.875688,102.0,232382.0,0.204954
9,AJU >> CPV,481.901179,157.755221,279.940688,1894.821635,73.0,3000.0,0.327360
10,AJU >> CWB,540.488246,125.251507,262.465729,1042.521437,102.0,140552.0,0.231738
11,AJU >> CXJ,652.913836,172.045389,156.622610,2814.352175,95.0,3094.0,0.263504
12,AJU >> CZS,947.672858,385.630695,278.230552,2256.147272,40.0,184.0,0.406924
13,AJU >> FEN,693.877116,249.301646,367.497499,1775.549761,101.0,3891.0,0.359288
14,AJU >> FLN,609.929278,119.804695,407.536845,1136.029413,102.0,66737.0,0.196424